### ISSUE TITLE
docker::cleanup feature

### ISSUE THREAD

**Issue by atomic-penguin** [bflad/chef-docker#148]
Since docker tends to leave lots of little intermediate container artifacts lying around.  It might be useful to have a share-able cleanup recipe that does something like [this](http://blog.stefanxo.com/2014/02/clean-up-after-docker/) via cron with a tunable frequency knob.

Otherwise this would be something I cram into our $org-jenkins cookbook.  I could see how such a feature might be useful on developer machines, however.

**Comment by someara** [comment]
With the move to a resource based cookbook, it feels like this should be implemented as a separate cookbook... 

An implementation of this would likely involve set management via resource collection introspection, which feels like something that would involve a lot of exceptions and edge cases unsuitable for a generically reusable cookbook.

Closing for now due to its age... (over a year)
