### ISSUE TITLE
Centos 7 Systemd storage_driver

### ISSUE THREAD

**Issue by mdbishop** [bflad/chef-docker#272]
On Centos7 (perhaps other SystemD based distros, just moving over from Debian), the recipe writes out to /etc/sysconfig/docker DOCKER_OPTS as expected.  However systemd ignores any storage related parameters unless contained in a separate docker-storage file.

So, the following in /etc/sysconfig/docker refuses to pick up the storage directives:
```
DOCKER_OPTS=' --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock --graph=/local/docker --restart=false --storage-driver=btrfs'
```

After adding the following to /etc/sysconfig/docker-storage all works as expected:
```
DOCKER_STORAGE_OPTIONS= --graph=/local/docker  --storage-driver=btrfs
```

Similar issues exist for networking for which I'll open another issue.

**Comment by cywjackson** [comment]
we ran into this on amazon linux . I wasn't sure how adding a separate file  /etc/sysconfig/docker-storage will help to start with, because it is not referenced anywhere in this cookbook. But when i installed docker separately via on a new box (without chef, so just pure yum install on the new amazon linux ec2), i could see that new file is being sourced in /etc/init.d/docker, and the arguments are being referenced.

But looking at https://github.com/bflad/chef-docker/blob/master/templates/amazon/docker.sysv.erb#L49 , (and L31 for that matter), looks like the issue can be simply addressed via declaring `other_args` for the options in https://github.com/bflad/chef-docker/blob/master/templates/default/docker.sysconfig.erb (not everything goes there, such as logfile)

Though the approach does feel hacky. Also noticed diff docker version seems does thing differently.

**Comment by bflad** [comment]
@mdbishop I wonder if you just need the CentOS 7 support coming by default in 0.37.0 (soon to be released)? A modern CentOS 7 service install/config should be systemd based (/usr/lib/systemd/system/docker*) instead of SysV (/etc/init.d/docker). systemd doesn't reference files like SysV did.

@cywjackson I can't think of a reason off the top of my head why `other_args` would be required somehow. In the end, all these options are appended to the docker daemon command line.

Otherwise this looks quite annoying. From the sounds of it here, looks like we might need to make some things more platform aware such as:
* `daemon_cli_args` helper (maybe new `daemon_cli_storage_args`?)
* `docker-service` sysconfig template
* `docker::sysv` recipe

This would require some digging to come up with the correct solution. Any help or more information is appreciated, thanks!

**Comment by cywjackson** [comment]
@bflad  because of https://github.com/bflad/chef-docker/blob/master/templates/amazon/docker.sysv.erb#L49 . notice DOCKER_OPTS (and all other arguments, like the pid file, the log file are not used here)

**Comment by someara** [comment]
This should be fixed up with the docker_service resource as of 0.40.x
