### ISSUE TITLE
docker_container polling operations are not always desirable. 

### ISSUE THREAD

**Issue by someara** [bflad/chef-docker#510]
It turns out that the fix for #498 causes test-kitchen runs to go from a few minutes to over 20.

``` 
-----> Kitchen is finished. (23m40.86s)
zlib(finalizer): the stream was freed prematurely.

real    23m41.562s
user    0m9.277
sys     0m2.473s
laptop:~/src/opscode-cookbooks/docker$
```

We should probably add a property on the resource to make this optional while still letting redeploy be safe

-s

**Comment by chasebolt** [comment]
Do you know what was hanging it up? Containers traversing to the running
state must take a lot longer than expected...

**Comment by someara** [comment]
That's pretty much it. I was also surprised. Apparently the old behavior
was just "fork and forget"
-s

**Comment by chasebolt** [comment]
What actually could be happening is a container go from created  > running
> completed faster than the wait method checks. This would cause running to
be false (since it already completed) and the wait to do a full timeout
cycle of 20 seconds.

We need to check one of the timestamp fields as well to catch this case.

**Comment by jperville** [comment]
Yes, the polling for container running makes the kitchen run very slow (especially if the container crashes for another reason, then we have to wait 20 seconds at least per container)... We could probably reduce the "sleep 1" to a shorter delay to make this more reactive.

**Comment by CVTJNII** [comment]
I don't believe the solution in #511 was the correct one, and it may have masked some other problems.  While working on #679 I modified this logic back to the default and I noticed that the full timeout was being hit, even though the container was in the desired state.  The timeout appears to be due to the fact that the container object is not being updated in the state() method.  As such wait_running_state() will block for the full timeout unless the container is already in the desired state as changes are not registered.  My current assumption is that multi-operation actions the calls to individual actions will cause load_current_value to refresh the container object.

I have a patch in 06ca5d6 which I believe resolves this and #679 completely which I'm still testing.  A PR may be delayed until my company gets a CCLA in place.

**Comment by chasebolt** [comment]
Do you have a working test case for this that you can gist?

**Comment by CVTJNII** [comment]
@chasebolt What kind of a tests are you looking for?  I figured this out with prints and 'watch docker ps' running in another window, so I don't have an automated test case.  I do have a test cookbook where redeploy takes 20s without the patch to state() but that's no good for automation.

I considered making wait_running_state() throw an exception on timeout, as something is probably wrong if the container doesn't reach the desired state in 20s and that would cause test failures, but I wasn't sure if others would agree.

**Comment by chasebolt** [comment]
You are correct on the container.info['State'] is returning stale info and your patched change for that looks good :+1:

**Comment by CVTJNII** [comment]
I'm curious what others opinions are on the following patch:

https://github.com/CVTJNII/docker/commit/ededfcfbd811860bb5b80ba62db6884004939038

This will cause wait_running_state() to throw an exception if it times out.  I believe this is better behavior as a) the container not changing state in 20s is bad and probably not a case where Chef can keep trundling along, b) this allows wait_running_state to be wrapped in a with_retries block which is useful in resolving some races I've been seeing in my testing and c) this should cause tests to fail on the timeout case, which I believe would meet test requirements for 06ca5d6.

I plan to open a PR with this once we have a CCLA in place, but wish to get opinions on it in the mean time.
